name: tahavol_sangin
description: اپلیکیشن حمل و نقل هوشمند تحول سنگین
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  image_picker: ^1.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  intl: ^0.19.0
  shamsi_date: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700
